name: Output Workflow

on:
    push:
        branches:
            - 'main'



jobs:
    output-info:
        runs-on: ubuntu-latest
        steps:
            - name: Test the output
              id: test
              run: echo "value=hello" >>$GITHUB_OUTPUT


            - name: Refer the Output
              run: echo "The value is ${{steps.test.outputs.value}} "
